### ISSUE TITLE
Never returns anything

### ISSUE THREAD

**Issue by numanelahi** [noonEng/etlJS#2]
https://github.com/noonEng/etlJS/blob/c1c38058a3a8bf7596d1e1a5cae4a898b7c38eaa/src/SynchronousPost.js#L31

This function will always return `undefined`.

**Comment by akshit-sawhney** [comment]
Since this framework is consuming browser storage by the use of store module, and the store module, on any call to store the data in it(store.set(value, data)) returns an undefined, so it doesn't makes sense to overwrite it. Also, the code has been moved to https://github.com/noonAcademy/etlJS repositories, so, please raise the issues there, since we won't be maintaining this one.
